fix: MinGW gvmap.sh detection logic
CI has begun failing on MinGW:

  FAILED ci/tests.py::test_existence[gvmap.sh] - AssertionError: gvmap.sh has been resurrected in the cmake build on None. Please remove skip.
  assert WindowsPath('C:/Graphviz/bin/gvmap.sh') is None
   +  where WindowsPath('C:/Graphviz/bin/gvmap.sh') = which('gvmap.sh')
  FAILED tests/test_tools.py::test_tools[gvmap.sh] - OSError: [WinError 193] %1 is not a valid Win32 application

Comparing the CI logs from commit 71aed634f23dc1af5c7823daabe978964d6a4218
against recent failing MRs, it can be seen that Python in MinGW has moved from
3.11.10 to 3.12.7. Quoting some text from commit
97b0c0b991dfad9c8b434576ea0bdd350143c315:

  > This test began failing due to gvmap.sh unexpectedly existing. As diagnosed
  > by Magnus:
  >
  > > I diffed a full log file from a successful job with one from a failing one
  > > and the only tangible difference I could find was an upgrade of Python
  > > from 3.11.5 to 3.12.0. Indeed, this is what What’s New In Python 3.12¹
  > > says:
  > >
  > > > shutil
  > > > …
  > > > shutil.which() now consults the `PATHEXT` environment variable to find
  > > > matches within `PATH` on Windows even when the given `cmd` includes a
  > > > directory component. (Contributed by Charles Machalow in gh-103179.)
  > > >
  > > > shutil.which() will call `NeedCurrentDirectoryForExePathW` when querying
  > > > for executables on Windows to determine if the current working directory
  > > > should be prepended to the search path. (Contributed by Charles Machalow
  > > > in gh-103179.)
  > > >
  > > > shutil.which() will return a path matching the `cmd` with a component
  > > > from `PATHEXT` prior to a direct match elsewhere in the search path on
  > > > Windows. (Contributed by Charles Machalow in gh-103179.)
  > >
  > > I don't really understand what all this means, but it sounds quite
  > > suspicious to me anyway.

So it looks like the previous Python change that made it into the Windows
ecosystem has now propagated to MinGW.